import Head from 'next/head'
import Otp from './otp'
export default function Home() {
  return (
    <>
      <Head>
        <title>My Story Book</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     {/* <Otp/> */}
    </>
  )
}
